# Generated by Django 2.2.6 on 2019-10-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ST', 'Student'), ('JS', 'jobseeker'), ('EM', 'employed')], default='ST', max_length=2)),
            ],
        ),
    ]
