# Generated by Django 2.2.6 on 2019-11-04 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ammanarul', '0002_auto_20191101_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='post',
            name='display_upto',
            field=models.DateField(default=datetime.date(2019, 12, 2)),
        ),
    ]
